image:
  file: .gitpod.Dockerfile
tasks:
  - name: Strapi
    init: >
      cd /workspace/tip-blog/api &&
      yarn install &&
      echo ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} >> .env &&
      echo API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }}>> .env &&
      echo APP_KEYS=${{ secrets.APP_KEYS }} >> .env &&
      echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env &&
      gp sync-done strapi
    command: yarn develop
#  - name: Vue.js
#    init: |
#      cd /workspace/tip-blog/client &&
#      gp sync-await strapi
#      yarn install
#    command: yarn dev
ports:
  - port: 1337
    onOpen: open-browser
    visibility: public
  - port: 5173
    onOpen: open-browser
    visibility: public
